server:
  port: 8888
spring:
  application:
    name: zuul

#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: service-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  httpclient:
    enabled: true

logging:
  level:
    cn.sunguolei.blog.servicezuul: debug
#    com.netflix: debug