server:
  port: 8764
spring:
  application:
    name: note
  datasource:
    url: jdbc:mysql://192.168.154.219:3306/ying_note?characterEncoding=UTF-8&useSSL=false
    username: yingnote
    password: Yingnote@2018
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.sunguolei.blog.noteservice.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.sunguolei.blog.noteservice: debug
    com.netflix.feign: debug
#    com.netflix: debug